# Diretórios locais (relativos ao projeto)
ARDUINO_DIR = $(realpath ../arduino-1.6.3)
ARDMK_DIR   = $(realpath ../arduino-makefile)

# Configuração da placa
BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM0
ARDUINO_LIBS = Wire

# Inclusão do Makefile principal
include $(ARDMK_DIR)/Arduino.mk
