//!
//! @file main.cpp
//!
//! @brief This file creates all the project's tasks.
//!
//! @author João Cláudio Elsen Barcellos <joaoclaudiobarcellos@gmail.com>
//! @version 0.0.0
//!
//! @date 06/08/2024
//!

//! External headers
#include <FreeRTOS.h>
#include <task.h>               

//! Project-specific headers
#include "./src-gen/Statechart.h"   //!< File generated by Itemis CREATE

#include "pico/stdlib.h"            

#include "RPPicoCallback.h"         

#include "./config/tasks.h"

int main(void)
{
    //! Create all the prject's tasks
    create_tasks();
    //! Start the scheduler
    vTaskStartScheduler();
    //! Should never reach it
    return 0;
}
